# Generated by Django 4.2.26 on 2025-11-20 08:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0002_userprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chantier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('date_debut', models.DateField()),
                ('date_fin_prevue', models.DateField()),
                ('date_fin_reelle', models.DateField(blank=True, null=True)),
                ('budget', models.DecimalField(decimal_places=2, max_digits=12)),
                ('statut', models.CharField(choices=[('planifie', 'Planifié'), ('en_cours', 'En Cours'), ('termine', 'Terminé'), ('annule', 'Annulé')], default='planifie', max_length=20)),
                ('avancement', models.IntegerField(default=0, help_text="Pourcentage d'avancement (0-100)")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('chef_chantier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chantiers_diriges', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Chantier',
                'verbose_name_plural': 'Chantiers',
            },
        ),
        migrations.CreateModel(
            name='Fournisseur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('contact', models.CharField(blank=True, max_length=200)),
                ('telephone', models.CharField(blank=True, max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('adresse', models.CharField(blank=True, max_length=300)),
                ('specialite', models.CharField(blank=True, help_text='Domaine de spécialisation', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Fournisseur',
                'verbose_name_plural': 'Fournisseurs',
            },
        ),
        migrations.AlterModelOptions(
            name='client',
            options={'verbose_name': 'Client', 'verbose_name_plural': 'Clients'},
        ),
        migrations.AlterModelOptions(
            name='rapport',
            options={'verbose_name': 'Rapport', 'verbose_name_plural': 'Rapports'},
        ),
        migrations.AddField(
            model_name='facture',
            name='date_echeance',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='facture',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='facture',
            name='numero',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='facture',
            name='statut',
            field=models.CharField(choices=[('brouillon', 'Brouillon'), ('envoyee', 'Envoyée'), ('payee', 'Payée'), ('annulee', 'Annulée')], default='brouillon', max_length=20),
        ),
        migrations.AddField(
            model_name='rapport',
            name='type_rapport',
            field=models.CharField(choices=[('journalier', 'Rapport Journalier'), ('hebdomadaire', 'Rapport Hebdomadaire'), ('mensuel', 'Rapport Mensuel'), ('incident', "Rapport d'Incident")], default='journalier', max_length=20),
        ),
        migrations.AlterField(
            model_name='factureline',
            name='facture',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='core.facture'),
        ),
        migrations.AlterField(
            model_name='factureline',
            name='montant',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='factureline',
            name='prix_unitaire',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='factureline',
            name='quantite',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=8),
        ),
        migrations.AlterField(
            model_name='rapport',
            name='auteur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rapports', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='rapport',
            name='contenu',
            field=models.TextField(),
        ),
        migrations.CreateModel(
            name='Personnel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('chef_chantier', 'Chef de Chantier'), ('maitre_ouvrier', 'Maître Ouvrier'), ('ouvrier', 'Ouvrier'), ('apprenti', 'Apprenti')], default='ouvrier', max_length=20)),
                ('taux_horaire', models.DecimalField(decimal_places=2, max_digits=8)),
                ('telephone', models.CharField(blank=True, max_length=20)),
                ('adresse', models.CharField(blank=True, max_length=300)),
                ('date_embauche', models.DateField()),
                ('est_actif', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('chantier_actuel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='personnel_actuel', to='core.chantier')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Personnel',
                'verbose_name_plural': 'Personnel',
            },
        ),
        migrations.CreateModel(
            name='Materiau',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('categorie', models.CharField(choices=[('construction', 'Matériaux de construction'), ('electricite', 'Électricité'), ('plomberie', 'Plomberie'), ('peinture', 'Peinture'), ('outillage', 'Outillage'), ('autre', 'Autre')], default='construction', max_length=50)),
                ('description', models.TextField(blank=True)),
                ('unite', models.CharField(default='unités', max_length=20)),
                ('quantite_stock', models.IntegerField(default=0)),
                ('seuil_minimum', models.IntegerField(default=0)),
                ('prix_unitaire', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fournisseur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='materiaux', to='core.fournisseur')),
            ],
            options={
                'verbose_name': 'Matériau',
                'verbose_name_plural': 'Matériaux',
            },
        ),
        migrations.AddField(
            model_name='chantier',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chantiers', to='core.client'),
        ),
        migrations.AddField(
            model_name='facture',
            name='chantier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='factures', to='core.chantier'),
        ),
        migrations.AddField(
            model_name='factureline',
            name='materiau',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lignes_facture', to='core.materiau'),
        ),
        migrations.AddField(
            model_name='rapport',
            name='chantier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rapports', to='core.chantier'),
        ),
    ]
