# Generated by Django 4.2.26 on 2025-12-26 12:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0003_chantier_fournisseur_alter_client_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=150)),
                ('prenom', models.CharField(max_length=150)),
                ('telephone', models.CharField(blank=True, max_length=30)),
                ('role', models.CharField(choices=[('OUVRIER', 'Ouvrier'), ('APPRENTI', 'Apprenti'), ('CHEF_CHANTIER', 'Chef de Chantier'), ('ADMIN', 'Administrateur')], max_length=20)),
                ('statut', models.CharField(choices=[('ACTIF', 'Actif'), ('INACTIF', 'Inactif'), ('SUSPENDU', 'Suspendu')], default='ACTIF', max_length=20)),
                ('date_embauche', models.DateField()),
                ('type_remuneration', models.CharField(choices=[('JOURNALIER', 'Journalier'), ('MENSUEL', 'Mensuel'), ('FORFAIT', 'Forfait')], max_length=20)),
                ('montant_remuneration', models.DecimalField(decimal_places=2, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employee', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Employé',
                'verbose_name_plural': 'Employés',
            },
        ),
        migrations.CreateModel(
            name='RapportChantier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('avancement', models.IntegerField(default=0)),
                ('problemes', models.TextField(blank=True)),
                ('commentaires', models.TextField(blank=True)),
                ('chantier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rapports_chantier', to='core.chantier')),
                ('chef_chantier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rapports_chantier', to='core.employee')),
            ],
            options={
                'verbose_name': 'Rapport de chantier',
                'verbose_name_plural': 'Rapports de chantier',
            },
        ),
        migrations.CreateModel(
            name='Presence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('statut', models.CharField(choices=[('PRESENT', 'Présent'), ('ABSENT', 'Absent'), ('RETARD', 'Retard')], max_length=10)),
                ('chantier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presences', to='core.chantier')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presences', to='core.employee')),
                ('valide_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='presences_validees', to='core.employee')),
            ],
            options={
                'verbose_name': 'Présence',
                'verbose_name_plural': 'Présences',
            },
        ),
        migrations.CreateModel(
            name='OuvrierDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metier', models.CharField(blank=True, max_length=100)),
                ('chef_responsable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ouvriers_responsables', to='core.employee')),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ouvrier_details', to='core.employee')),
            ],
        ),
        migrations.CreateModel(
            name='ChefChantierDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zone', models.CharField(blank=True, max_length=100)),
                ('prime_responsabilite', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='chef_details', to='core.employee')),
            ],
        ),
        migrations.CreateModel(
            name='Affectation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField(blank=True, null=True)),
                ('actif', models.BooleanField(default=True)),
                ('chantier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='affectations', to='core.chantier')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='affectations', to='core.employee')),
            ],
            options={
                'verbose_name': 'Affectation',
                'verbose_name_plural': 'Affectations',
            },
        ),
        migrations.AddField(
            model_name='chantier',
            name='chef_chantier_employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chantiers_diriges_employee', to='core.employee'),
        ),
        migrations.AddConstraint(
            model_name='affectation',
            constraint=models.UniqueConstraint(condition=models.Q(('actif', True)), fields=('employee',), name='unique_active_affectation_per_employee'),
        ),
    ]
