# Generated by Django 4.2.26 on 2025-12-27 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_employee_rapportchantier_presence_ouvrierdetails_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='personnel',
            name='formation',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='personnel',
            name='metier',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='personnel',
            name='prime_responsabilite',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='personnel',
            name='specialite',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='personnel',
            name='tuteur',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='personnel',
            name='zone',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
