# Generated by Django 4.2.26 on 2025-12-27 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_personnel_formation_personnel_metier_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='personnel',
            name='salaire_mensuel',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='personnel',
            name='taux_horaire',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
    ]
