# Generated by Django 4.2.26 on 2025-12-27 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_personnel_salaire_mensuel_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='personnel',
            old_name='taux_horaire',
            new_name='taux_journalier',
        ),
    ]
