# Generated by Django 4.2.26 on 2026-01-18 22:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0009_alter_userprofile_role_personnelpayment'),
    ]

    operations = [
        migrations.CreateModel(
            name='FactureActionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('mark_paid', 'Marqué payé'), ('mark_unpaid', 'Marqué impayé'), ('cancel', 'Annulée'), ('reopen', 'Rouverte'), ('partial_payment', 'Paiement partiel')], max_length=40)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('facture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='action_logs', to='core.facture')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Journal action facture',
                'verbose_name_plural': 'Journaux actions facture',
            },
        ),
        migrations.CreateModel(
            name='Commande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.IntegerField()),
                ('statut', models.CharField(choices=[('preparée', 'Préparée'), ('envoyee', 'Envoyée'), ('recue', 'Reçue'), ('annulee', 'Annulée')], default='preparée', max_length=20)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('demandeur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commandes_demandees', to=settings.AUTH_USER_MODEL)),
                ('fournisseur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commandes', to='core.fournisseur')),
                ('materiau', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commandes', to='core.materiau')),
            ],
            options={
                'verbose_name': 'Commande',
                'verbose_name_plural': 'Commandes',
            },
        ),
    ]
